### ISSUE TITLE
CORS doesnt seem to be supported yet

### ISSUE THREAD

**Issue by habdelra** [najaxjs/najax#32]
When I make a request for a resource the requires CORS, it looks like the CORS headers cannot be accessed. I get see this response:

```
najax: method jqXHR."getAllResponseHeaders" not implemented
Trace
    at Object.getAllResponseHeaders (/Users/hassan/codez/ember-fastboot-deploy/node_modules/najax/lib/najax.js:102:15)
    at ClientRequest.errorHandler (/Users/hassan/codez/ember-fastboot-deploy/node_modules/najax/lib/najax.js:119:34)
    at ClientRequest.emit (events.js:107:17)
    at TLSSocket.socketErrorListener (_http_client.js:272:9)
    at TLSSocket.emit (events.js:129:20)
    at TLSSocket.<anonymous> (_tls_wrap.js:940:18)
    at TLSSocket.emit (events.js:104:17)
    at TLSSocket._finishInit (_tls_wrap.js:458:8)
```

I 'm guessing that https://github.com/najaxjs/najax/blob/master/lib/najax.js#L118 needs to be implemented in order to support CORS?

**Comment by habdelra** [comment]
Nevermind--i see https://github.com/najaxjs/najax/commit/d44cf7b16117ae570d750e7d8a773168a6a70604 takes care of this.
